"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenoaisam (https://sketchfab.com/xenoaisam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/megumin-148da44b16dc4dd9ab102606d6d46ebd
Title: Megumin
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MeguminHead_Head_0: THREE.Mesh
    MeguminHead_Eye_R_0: THREE.Mesh
    MeguminHead_Eye_L_0: THREE.Mesh
    MeguminHead_Expression_0: THREE.Mesh
    MeguminHair_Hair_0: THREE.Mesh
    MeguminBody_Body_0: THREE.Mesh
    MeguminHat_Hat_0: THREE.Mesh
    MeguminLeg_Leg_0: THREE.Mesh
    MeguminHand_Body_0: THREE.Mesh
    MeguminCape_Leg_0: THREE.Mesh
    MeguminStaff_Megumin_staff_0: THREE.Mesh
  }
  materials: {
    Head: THREE.MeshBasicMaterial
    Eye_R: THREE.MeshBasicMaterial
    Eye_L: THREE.MeshBasicMaterial
    Expression: THREE.MeshBasicMaterial
    Hair: THREE.MeshBasicMaterial
    Body: THREE.MeshBasicMaterial
    material: THREE.MeshBasicMaterial
    material_7: THREE.MeshBasicMaterial
    Leg_0: THREE.MeshBasicMaterial
    Megumin_staff: THREE.MeshBasicMaterial
  }
}

export  function MeguminModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/megumin.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.442]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeguminHead_Head_0.geometry}
          material={materials.Head}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeguminHead_Eye_R_0.geometry}
          material={materials.Eye_R}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeguminHead_Eye_L_0.geometry}
          material={materials.Eye_L}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeguminHead_Expression_0.geometry}
          material={materials.Expression}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeguminBody_Body_0.geometry}
          material={materials.Body}
          position={[0, -1.679, 66.069]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeguminLeg_Leg_0.geometry}
          material={materials.material_7}
          position={[0, -1.679, 66.069]}
        />
      </group>
      <group position={[-30.456, 48.974, 0.55]} rotation={[-0.887, 0.364, 2.379]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeguminStaff_Megumin_staff_0.geometry}
          material={materials.Megumin_staff}
          position={[0.138, 0, -40.688]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MeguminHair_Hair_0.geometry}
        material={materials.Hair}
        position={[0, 65.821, 1.265]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MeguminHat_Hat_0.geometry}
        material={materials.material}
        position={[0.282, 67.33, 1.273]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MeguminHand_Body_0.geometry}
        material={materials.Body}
        position={[0, 0, -0.442]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MeguminCape_Leg_0.geometry}
        material={materials.Leg_0}
        position={[0, 40.557, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/megumin.glb')

