/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: virus (https://sketchfab.com/lvirusl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cozy-workplace-corner-7b99f309820a4349b3cddb0d6cc7ac79
Title: Cozy workplace corner
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Book002_White_0: THREE.Mesh
    Book001_Orange_0: THREE.Mesh
    Monoblock_Metal_0: THREE.Mesh
    Monoblock_White_0: THREE.Mesh
    Monoblock_Screen_0: THREE.Mesh
    Tourbox_controller_Black1_0: THREE.Mesh
    Soft_Paper_Lamp_Paper_Lamp_0: THREE.Mesh
    window_plane_Light_Outside_0: THREE.Mesh
    Poster_Photo_0: THREE.Mesh
    Curtain_L_Curtains_0: THREE.Mesh
  }
  materials: {
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshPhysicalMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    Screen: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
    Photo: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
  }
}

export function RoomModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/oproom.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Book002_White_0.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Book001_Orange_0.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monoblock_Metal_0.geometry}
        material={materials.PaletteMaterial001}
        position={[0.093, 0.997, 0.113]}
        rotation={[-Math.PI / 2, 0, 0.07]}
        scale={1.417}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monoblock_White_0.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.445, 1.514, -0.025]}
        rotation={[-Math.PI / 2, 0, 0.07]}
        scale={1.218}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monoblock_Screen_0.geometry}
        material={materials.Screen}
        position={[-1.011, 1.639, 0.017]}
        rotation={[-Math.PI / 2, 0, 0.07]}
        scale={0.571}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tourbox_controller_Black1_0.geometry}
        material={materials.PaletteMaterial003}
        position={[0.027, 1.294, 0.005]}
        rotation={[-Math.PI / 2, 0, 0.243]}
        scale={2.12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Soft_Paper_Lamp_Paper_Lamp_0.geometry}
        material={materials.PaletteMaterial004}
        position={[-0.899, 1.229, 1.077]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.window_plane_Light_Outside_0.geometry}
        material={materials.PaletteMaterial005}
        position={[0.865, 1.54, -1.616]}
        scale={[0.578, 1.104, 1.87]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Poster_Photo_0.geometry}
        material={materials.Photo}
        position={[-0.368, 2.203, -1.295]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtain_L_Curtains_0.geometry}
        material={materials.PaletteMaterial006}
        position={[0.943, 1.744, -1.209]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.177, 0.85, 1.177]}
      />
    </group>
  )
}

useGLTF.preload('/models/oproom.glb')

